language: node_js

node_js:
- 10

addons:
  yarn: 1.17.3

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

install:
- yarn

script:
- yarn test

after_success:
- bash <(curl -s https://codecov.io/bash)

after_failure:
- cat ~/.npm/_logs/*-debug.log

notification:
  email:
    recipients:
      - dev.moreal@gmail.com
    on_success: changed
    on_failure: changed
