language: node_js

node_js:
- 10

addons:
  yarn: 1.17.3
  apt:
  packages:
    - xvfb

before_install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
- yarn

script:
- yarn test

after_success:
- bash <(curl -s https://codecov.io/bash)

after_failure:
- cat ~/.npm/_logs/*-debug.log

notification:
  email:
    recipients:
      - dev.moreal@gmail.com
    on_success: changed
    on_failure: changed
